ignore:
  - "*/cmd/main.go"

coverage:
  status:
    project:
      app:
        paths:
          - "!**/test/"
          - "!**/bddtest/"
      tests:
        paths:
          - "**/test/"
          - "**/bddtest/"
        informational: true
