// gen-crd generates the complete CRD with provider config schemas.
// It reads the base CRD generated by controller-gen, patches it with
// the oneOf schema from all registered providers, and prints to stdout.
//
// Usage: go run ./cmd/gen-crd > charts/secret-manager/crds/clientsecrets.yaml
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/lukasngl/secret-manager/internal/adapter"
	_ "github.com/lukasngl/secret-manager/internal/adapter/azure"
	"github.com/lukasngl/secret-manager/internal/crd"
)

func main() {
	basePath := flag.String("base", crd.DefaultBaseCRDPath, "Path to base CRD file")
	flag.Parse()

	crdBytes, err := crd.Generate(*basePath, adapter.DefaultRegistry())
	if err != nil {
		fmt.Fprintf(os.Stderr, "error generating CRD: %v\n", err)
		os.Exit(1)
	}

	fmt.Print(string(crdBytes))
}
