// Code generated by godogen; DO NOT EDIT.

package e2e

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Then(`^the mock provider should have received at least (\d+) provision calls$`, r1.theMockProviderShouldHaveReceivedAtLeastProvisionCalls)
	sc.Then(`^the mock provider should have received at least (\d+) provision calls within (\d+) seconds$`, r1.theMockProviderShouldHaveReceivedAtLeastProvisionCallsWithin)
	sc.Then(`^the mock provider should have received at least (\d+) delete key calls within (\d+) seconds$`, r1.theMockProviderShouldHaveReceivedAtLeastDeleteKeyCallsWithin)
}
