// Code generated by godogen; DO NOT EDIT.

package bddtest

import "github.com/cucumber/godog"

// InitializeSuite registers steps defined in "suite.go" with the [godog.ScenarioContext].
func InitializeSuite[T1 Object](sc *godog.ScenarioContext, r1 *Suite[T1]) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Before(r1.before)
	sc.After(r1.after)
	sc.Given(`^a Kubernetes cluster is running$`, r1.aKubernetesClusterIsRunning)
	sc.Given(`^the CRDs are installed$`, r1.theCRDsAreInstalled)
	sc.Given(`^the operator is running$`, r1.theOperatorIsRunning)
	sc.When(`^I create a ClientSecret:$`, r1.iCreateAClientSecret)
	sc.When(`^I create a ClientSecret "([^"]*)" with:$`, r1.iCreateAClientSecretNamed)
	sc.When(`^I try to create a ClientSecret "([^"]*)" with:$`, r1.iTryToCreateAClientSecretNamed)
	sc.When(`^I update the ClientSecret "([^"]*)" with:$`, r1.iUpdateTheClientSecretWith)
	sc.When(`^I delete the ClientSecret "([^"]*)"$`, r1.iDeleteTheClientSecret)
	sc.When(`^I expire the credentials for ClientSecret "([^"]*)"$`, r1.iExpireTheCredentialsForClientSecret)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)"$`, r1.theClientSecretShouldHavePhase)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)" within (\d+) seconds$`, r1.theClientSecretShouldHavePhaseWithin)
	sc.Then(`^the ClientSecret "([^"]*)" should not exist within (\d+) seconds$`, r1.theClientSecretShouldNotExistWithin)
	sc.Then(`^the ClientSecret "([^"]*)" status should contain message "([^"]*)"$`, r1.theClientSecretStatusShouldContainMessage)
	sc.Then(`^the ClientSecret "([^"]*)" should have (\d+) active keys$`, r1.theClientSecretShouldHaveActiveKeys)
	sc.Then(`^the ClientSecret "([^"]*)" should have at least (\d+) active keys within (\d+) seconds$`, r1.theClientSecretShouldHaveAtLeastActiveKeysWithin)
	sc.Then(`^a Secret "([^"]*)" should exist$`, r1.aSecretShouldExist)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)"$`, r1.theSecretShouldContainKey)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)" within (\d+) seconds$`, r1.theSecretShouldContainKeyWithin)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)" with value "([^"]*)"$`, r1.theSecretShouldContainKeyWithValue)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)" with value "([^"]*)" within (\d+) seconds$`, r1.theSecretShouldContainKeyWithValueWithin)
	sc.Then(`^the Secret "([^"]*)" should be owned by ClientSecret "([^"]*)"$`, r1.theSecretShouldBeOwnedByClientSecret)
	sc.Then(`^the operation should have failed$`, r1.theOperationShouldHaveFailed)
	sc.Then(`^the operation should have failed with "([^"]*)"$`, r1.theOperationShouldHaveFailedWith)
	sc.Then(`^the Secret "([^"]*)" should not exist$`, r1.theSecretShouldNotExist)
}
