// Code generated by godogen; DO NOT EDIT.

package e2e

import "github.com/cucumber/godog"

// InitializeAzureSteps registers steps defined in "azure_steps.go" with the [godog.ScenarioContext].
func InitializeAzureSteps(sc *godog.ScenarioContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Given(`^Azure credentials are configured$`, azureCredentialsAreConfigured)
	sc.When(`^I validate config:$`, iValidateConfig)
	sc.Then(`^validation should fail with "([^"]*)"$`, validationShouldFailWith)
	sc.Then(`^validation should succeed$`, validationShouldSucceed)
	sc.When(`^I provision credentials for app "([^"]*)" with:$`, iProvisionCredentialsForAppWith)
	sc.Given(`^I have provisioned credentials for app "([^"]*)"$`, iHaveProvisionedCredentialsForApp)
	sc.Then(`^the provisioning should succeed$`, theProvisioningShouldSucceed)
	sc.Then(`^the provisioning should fail with "([^"]*)"$`, theProvisioningShouldFailWith)
	sc.Then(`^the result should contain key "([^"]*)"$`, theResultShouldContainKey)
	sc.Then(`^the result should have a valid key ID$`, theResultShouldHaveAValidKeyID)
	sc.Then(`^the result key "([^"]*)" should match pattern "([^"]*)"$`, theResultKeyShouldMatchPattern)
	sc.Then(`^the result key "([^"]*)" should equal "([^"]*)"$`, theResultKeyShouldEqual)
	sc.Then(`^the result key "([^"]*)" should be a number greater than (\d+)$`, theResultKeyShouldBeNumberGreaterThan)
	sc.When(`^I delete the provisioned key$`, iDeleteTheProvisionedKey)
	sc.When(`^I delete key "([^"]*)" for app "([^"]*)"$`, iDeleteKeyForApp)
	sc.Then(`^the deletion should succeed$`, theDeletionShouldSucceed)
	sc.Then(`^the deletion should fail with "([^"]*)"$`, theDeletionShouldFailWith)
}
