// Code generated by godogen; DO NOT EDIT.

package e2e

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Before(beforeScenario)
	sc.After(afterScenario)
	sc.Given(`^a Kubernetes cluster is running$`, aKubernetesClusterIsRunning)
	sc.Given(`^the CRDs are installed$`, theCRDsAreInstalled)
	sc.Given(`^the operator is running$`, theOperatorIsRunning)
	sc.When(`^I create a ClientSecret:$`, iCreateAClientSecret)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)"$`, theClientSecretShouldHavePhase)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)" within (\d+) seconds$`, theClientSecretShouldHavePhaseWithin)
	sc.Then(`^a Secret "([^"]*)" should exist$`, aSecretShouldExist)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)"$`, theSecretShouldContainKey)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)" with value "([^"]*)"$`, theSecretShouldContainKeyWithValue)
}
