// Code generated by godogen; DO NOT EDIT.

package e2e

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Before(beforeScenario)
	sc.After(afterScenario)
	sc.Given(`^a Kubernetes cluster is running$`, aKubernetesClusterIsRunning)
	sc.Given(`^the CRDs are installed$`, theCRDsAreInstalled)
	sc.Given(`^the operator is running$`, theOperatorIsRunning)
	sc.When(`^I create a ClientSecret:$`, iCreateAClientSecret)
	sc.When(`^I update the ClientSecret "([^"]*)" with:$`, iUpdateTheClientSecretWith)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)"$`, theClientSecretShouldHavePhase)
	sc.Then(`^the ClientSecret "([^"]*)" should have phase "([^"]*)" within (\d+) seconds$`, theClientSecretShouldHavePhaseWithin)
	sc.Then(`^a Secret "([^"]*)" should exist$`, aSecretShouldExist)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)"$`, theSecretShouldContainKey)
	sc.Then(`^the Secret "([^"]*)" should contain key "([^"]*)" with value "([^"]*)"$`, theSecretShouldContainKeyWithValue)
	sc.Then(`^the Secret "([^"]*)" should not exist$`, theSecretShouldNotExist)
	sc.Then(`^the Secret "([^"]*)" should not exist within (\d+) seconds$`, theSecretShouldNotExistWithin)
	sc.When(`^I delete the ClientSecret "([^"]*)"$`, iDeleteTheClientSecret)
	sc.Then(`^the ClientSecret "([^"]*)" should not exist within (\d+) seconds$`, theClientSecretShouldNotExistWithin)
	sc.Then(`^the ClientSecret "([^"]*)" status should contain message "([^"]*)"$`, theClientSecretStatusShouldContainMessage)
	sc.Then(`^the mock provider should have received (\d+) provision calls$`, theMockProviderShouldHaveReceivedProvisionCalls)
	sc.Then(`^the mock provider should have received at least (\d+) provision calls$`, theMockProviderShouldHaveReceivedAtLeastProvisionCalls)
	sc.Then(`^the mock provider should have received (\d+) delete key calls$`, theMockProviderShouldHaveReceivedDeleteKeyCalls)
	sc.Then(`^the mock provider should have received at least (\d+) delete key calls within (\d+) seconds$`, theMockProviderShouldHaveReceivedAtLeastDeleteKeyCallsWithin)
	sc.When(`^I expire the credentials for ClientSecret "([^"]*)"$`, iExpireTheCredentialsForClientSecret)
	sc.Then(`^the ClientSecret "([^"]*)" should have (\d+) active keys$`, theClientSecretShouldHaveActiveKeys)
	sc.Then(`^the ClientSecret "([^"]*)" should have at least (\d+) active keys within (\d+) seconds$`, theClientSecretShouldHaveAtLeastActiveKeysWithin)
}
