package e2e

import (
	"os"
	"testing"

	"github.com/cucumber/godog"
	"github.com/cucumber/godog/colors"
)

func TestFeatures(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping e2e tests in short mode")
	}

	godogOpts := godog.Options{
		Format:      "pretty",
		Output:      colors.Colored(os.Stdout),
		Paths:       []string{"../../features"},
		Concurrency: 1,
	}

	status := godog.TestSuite{
		Name:                "secret-manager",
		ScenarioInitializer: InitializeSteps, // generated by godogen
		Options:             &godogOpts,
	}.Run()

	if status != 0 {
		t.Fatalf("godog tests failed with status %d", status)
	}
}
